version: '3.8'

services:
  # MySQL数据库服务
  db:
    image: mysql:8.0
    container_name: library-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: library_database
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - library-network

  # Spring Boot后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: library-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/library_database?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    networks:
      - library-network

  # Vue前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: library-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - library-network

# 定义挂载卷
volumes:
  mysql_data:

# 定义网络
networks:
  library-network:
    driver: bridge 